### PR TITLE
Remove Foundation shims

### PR DESCRIPTION
**Pull request by kateinoigakukun**
We recently unlocked many Foundation APIs on WASI, so we no longer need to provide shims for them. This commit updates the SwiftWasm toolchain version to the latest available, and removes the shims 😄 

The next nightly upstream release will resolve the SwiftPM test runner's build failure.

PS: It might be a good time to upstream swift-syntax changes if you are interested. (Or if you are busy and you are ok, I can upstream them based on your efforts.)

### CODE REVIEW

**Comment by kkk669** [comment]
Thank you. I had missed that.

**Comment by kateinoigakukun** [comment]
Feel free to close this in favor of #7

**Comment by kkk669** [comment]
> PS: It might be a good time to upstream swift-syntax changes if you are interested. (Or if you are busy and you are ok, I can upstream them based on your efforts.)

swift-syntax can be built for WASI basically as is. The purpose of this repository is to detect when it's broken, so I have only modified it to run its tests. For example, my fork of [swift-format](https://github.com/kkk669/swift-format) depends on apple/swift-syntax.

On the other hand, I have modified swift-format to build for WASI, and it still has shims around `FileManager.default.enumerator`.

**Comment by kateinoigakukun** [comment]
> I have only modified it to run its tests. For example, my fork of [swift-format](https://github.com/kkk669/swift-format) depends on apple/swift-syntax.

Ah! I missed that. Then, we don't have any essential changes to be upstreamed. 

> On the other hand, I have modified swift-format to build for WASI, and it still has shims around FileManager.default.enumerator.

Unfortunately the API is not ported at the moment due to missing `fts(3)` implementation in wasi-libc. We can provide it in theory without introducing any new system interface, so stay tuned for a while.

**Review by kkk669 — APPROVED** [review]

**Pull request merged**
